### ISSUE TITLE
ETHSCAN API

### ISSUE THREAD

**Issue by usert3r3r3** [jeremyfritzen/Ethereum-honey-pot#2]
what is difference between ETHSCANAPIKEY and EHTERSCANAPI, do i put the api in both of these?

**Comment by jeremyfritzen** [comment]
Hi,

There are no such variables. But there are: 
- **etherscanAPI**, which is the URL of the Etherscan API.
- **etherscanApiKey**, which is used to configure the API Key to request Etherscan API (etherscanAPI). This API Key allows you to authenticate and use the Etherscan API.

**Comment by usert3r3r3** [comment]
> Hi,
> 
> There are no such variables. But there are:
> 
>     * **etherscanAPI**, which is the URL of the Etherscan API.
> 
>     * **etherscanApiKey**, which is used to configure the API Key to request Etherscan API (etherscanAPI). This API Key allows you to authenticate and use the Etherscan API.

thanks for answer
also another problem with node, any idea how to fix?

ERROR: can't convert --gas-price-gwei to decimal: exponent is not numeric
Variable transactionHash not set. Trying switching network

**Comment by jeremyfritzen** [comment]
I close issue since it has been covered by[ another thread](https://github.com/jeremyfritzen/Ethereum-honey-pot/issues/3).
